apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: shaiacr.azurecr.io/containerapp
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: sc2
        
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: shaiacr.azurecr.io/apiofapp
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: sc2
        
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: app
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: api