apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: app
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: app
          servicePort: 3000
  - host:
    http:
      paths:
      - path: /api
        backend:
          serviceName: api
          servicePort: 4000